apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: initial-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*.kmaster.local"
    - kmaster.local
    port:
      name: http
      number: 80
      protocol: HTTP