# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   labels:
#     app_level: internal
#   name: istio-init
#   namespace: istio-system
# spec:
#   destination:
#     name: ""
#     namespace: istio-system
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     path: istio
#     repoURL: https://github.com/a10pepo/k8sraspberry
#     targetRevision: main
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     automated:
#       prune: true
#       selfHeal: true