---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app_level: internal
  name: nginx
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: applications
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/nginx
    repoURL: https://github.com/a10pepo/k8sraspberry
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true